### ISSUE TITLE
docker cannot be built on mac with M1 chips

### ISSUE THREAD

**Issue by chloejooo123** [MaciejMazurowski/duke-dbt-data#4]
I am trying to run the python env from docker using my Macbook and here's the error message I got:

```
 > [4/5] RUN pip install --no-cache-dir -r requirements.txt:                              
#8 1.040 Collecting imageio==2.9.0                                                        
#8 1.152   Downloading imageio-2.9.0-py3-none-any.whl (3.3 MB)                            
#8 1.475 Collecting jupyter==1.0.0                                                        
#8 1.488   Downloading jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)                        
#8 1.720 Collecting matplotlib==3.3.3
#8 1.733   Downloading matplotlib-3.3.3.tar.gz (37.9 MB)
#8 5.266 Collecting numpy==1.19.4
#8 6.105   Downloading numpy-1.19.4-cp38-cp38-manylinux2014_aarch64.whl (12.2 MB)
#8 6.316 Collecting pandas==1.1.4
#8 6.652   Downloading pandas-1.1.4-cp38-cp38-manylinux2014_aarch64.whl (9.6 MB)
#8 6.897 Collecting pydicom==2.1.1
#8 6.985   Downloading pydicom-2.1.1-py3-none-any.whl (1.9 MB)
#8 7.022 Collecting pylibjpeg==1.1.1
#8 7.098   Downloading pylibjpeg-1.1.1-py3-none-any.whl (29 kB)
#8 7.140 Collecting scikit-image==0.17.2
#8 7.671   Downloading scikit-image-0.17.2.tar.gz (29.8 MB)
#8 9.003     ERROR: Command errored out with exit status 1:
#8 9.003      command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-041kagsv/scikit-image_94a1d922703c4216997843686357d32c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-041kagsv/scikit-image_94a1d922703c4216997843686357d32c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cw2ezydk
#8 9.003          cwd: /tmp/pip-install-041kagsv/scikit-image_94a1d922703c4216997843686357d32c/
#8 9.003     Complete output (7 lines):
#8 9.003     Traceback (most recent call last):
#8 9.003       File "<string>", line 1, in <module>
#8 9.003       File "/tmp/pip-install-041kagsv/scikit-image_94a1d922703c4216997843686357d32c/setup.py", line 234, in <module>
#8 9.003         'build_ext': openmp_build_ext(),
#8 9.003       File "/tmp/pip-install-041kagsv/scikit-image_94a1d922703c4216997843686357d32c/setup.py", line 58, in openmp_build_ext
#8 9.003         from numpy.distutils.command.build_ext import build_ext
#8 9.003     ModuleNotFoundError: No module named 'numpy'
#8 9.003     ----------------------------------------
#8 9.003 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#8 9.101 WARNING: You are using pip version 20.3.1; however, version 22.0.4 is available.
#8 9.101 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip install --no-cache-dir -r requirements.txt]: exit code: 1

```

but my friend can run the same code using his laptop, I suspect this is because I cannot download the sklearn version specified by the requirement, is there anyway I can fix this problem?

**Comment by mateuszbuda** [comment]
You're right, on M1 I had to adjust scikit-learn version, numpy, and then, as far as I remember, I forced downgrade of pylibjpeg version.
I will have to test that and push updated requirements for M1 in a separate branch.
Will notify you when it's done.
